<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit1a1f430f5f64ef848a7f924925891822
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit1a1f430f5f64ef848a7f924925891822::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit1a1f430f5f64ef848a7f924925891822::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
